//Warning: FILE heavily affected by recent edits in other files.
//Many functions have been rendered obsolete due to Socket.IO integration.
//DO NOT EDIT this file without checking previous functionality.
//File kept for reference for now.


// backend/server/controllers/messageController.js
// Message controller
//Handles message creation, retrieval, updating, deletion
//Might be extended later with more functionalities like attachments, read receipts, etc.

const Message = require('../dataBase/models/messageModel');
require('dotenv').config();
const mongoose = require('mongoose');

async function createMessage(req, res) {
    try {
        const { sender, content, chat } = req.body;
        if (!sender || !content || !chat) {
            return res.status(400).json({ message: "All fields are required" });
        }
        
        const newMessage = await Message.create({ sender, content, chat });
        return res.status(201).json({ message: "Message created successfully", messageData: newMessage });
    } catch (error) {
        console.error("Error creating message:", error);
        return res.status(500).json({ message: "Internal server error" });
    }
}

// Delete message by ID
//Might restrict this to message sender or admins later(very recommeded for production)
//For now, any user can delete any message(not ideal for production)
//Might be removed later to just edit message to "This message was deleted" instead of full deletion
//MOST LIKELY WILL BE REMOVED LATER AND MERGED WITH UPDATE FUNCTIONALITY
async function deleteMessage(req,res){
    try{
        const { messageId } = req.params;
    if( !messageId){
        return res.status(400).json({ message: "Message ID is required" });
    }

    const deletedMessage = await Message.findByIdAndDelete(messageId);
    if(!deletedMessage){
        return res.status(404).json({ message: "Message not found" });
    }
    return res.status(200).json({ message: "Message deleted successfully", messageData: deletedMessage });
} catch (error) {
    console.error("Error deleting message:", error);
    return res.status(500).json({ message: "Internal server error" });
}
}
// Get messages by chat ID
//Might be paginated later if chat has many messages
//Might get affected by Socket.IO integration later ( ALREASDY HANDLED VIA SOCKET.IO )
//Keeping for reference for now
async function getMessagesByChat(req, res) {
  try {
    const { chatId } = req.params;

    if (!chatId) {
      return res.status(400).json({ message: "Chat ID is required" });
    }

    if (!mongoose.Types.ObjectId.isValid(chatId)) {
      return res.status(400).json({ message: "Invalid Chat ID" });
    }

    // Fetch the last 50 messages for this chat, newest first
    const messages = await Message.find({ chat: chatId })
      .sort({ createdAt: -1 })  // newest first
      .limit(50);

    //Reverse to send oldest → newest
    messages.reverse();

    return res.status(200).json({ messages });
  } catch (error) {
    console.error("Error fetching messages:", error);
    return res.status(500).json({ message: "Internal server error" });
  }
}
// Update message by ID
//Might restrict this to message sender only later(recommended for production)
//For now, any user can update any message(not ideal for production)

async function updateMessage(req, res) {
    try{
        const { messageId } = req.params;
    const { content } = req.body;
    if( !messageId){
        return res.status(400).json({ message: "Message ID is required" });
    }

    const updatedData = {};
    if (content) updatedData.content = content;

    const updatedMessage = await Message.findByIdAndUpdate(messageId, updatedData, { new: true });
    if(!updatedMessage){
        return res.status(404).json({ message: "Message not found" });
    }
    return res.status(200).json({ message: "Message updated successfully", messageData: updatedMessage });
} catch (error) {
    console.error("Error updating message:", error);
    return res.status(500).json({ message: "Internal server error" });
}
}

module.exports = { createMessage, deleteMessage, getMessagesByChat, updateMessage };