// frontend/src/app/login/page.jsx
// Login page component
//Simple layout with background image and login form
//Not ideal but functionning for now
//Might redesign later with better UI/UX
//css Entirely generated by CHATGPT

"use client";
import React from "react";
import LoginForm from "@/components/forms/loginForm";
import './login.css';

export default function page() {
    return (
        <div className="login-page">
            <img src='/backGround.png' alt='Background' className='auth-image' />
            <LoginForm />
        </div>
    );
}
